/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example.app;

import org.example.list.LinkedList;

import static org.example.utilities.StringUtils.join;
import static org.example.utilities.StringUtils.split;
import static org.example.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

import javax.swing.JFrame;

public class App {
    public static void main(String[] args) {
        // 創建一個 JFrame 窗口
        JFrame frame = new JFrame("KTV Superstar");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setSize(800, 600); // 設置窗體大小
        frame.setVisible(true);  // 顯示窗體
    }
}
